import React,{useMemo,useState}from"react";
import*mammoth from"mammoth";
import*as pdfjsLib from"pdfjs-dist";
pdfjsLib.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/build/pdf.worker.mjs",import.meta.url).toString();
const STYLES=[["storybook","Hand-drawn Storybook"],["manga","Manga"],["manga90","90s Manga"],["anime90","90s Anime"],["comic","Comic Book"],["concept","Concept Art"],["watercolor","Watercolor"],["gothic","Dark Gothic"],["fairytale","Dark Fairytale"],["graphic","Graphic Novel"]];
const clean=s=>s.replace(/\\r/g,"").replace(/\\n{3,}/g,"\\n\\n").trim();
function splitScenes(t){const p=clean(t).split(/\\n\\s*\\n/).filter(Boolean);if(p.length<=8)return p.map((x,i)=>({id:i+1,text:x,title:"Scene "+(i+1)}));const out=[];let b="";p.forEach(x=>{b+=(b?"\\n\\n":"")+x;if(b.length>900){out.push(b);b=""}});if(b)out.push(b);return out.map((x,i)=>({id:i+1,text:x,title:"Scene "+(i+1)}))}
async function readFile(f){const n=f.name.toLowerCase();if(n.endsWith(".txt")||n.endsWith(".md"))return clean(await f.text());if(n.endsWith(".docx"))return clean((await mammoth.extractRawText({arrayBuffer:await f.arrayBuffer()})).value);if(n.endsWith(".pdf")){const pdf=await pdfjsLib.getDocument({data:await f.arrayBuffer()}).promise;let t="";for(let i=1;i<=pdf.numPages;i++){const pg=await pdf.getPage(i),c=await pg.getTextContent();t+=c.items.map(x=>x.str).join(" ")+"\\n\\n"}return clean(t)}throw Error("Supported files: PDF, DOCX, TXT, MD.")}
function promptFor(scene,style,ratio,char){return "Illustrated novel scene, "+style+", "+ratio+", cinematic composition. Preserve continuity and character identity. "+(char?"Character continuity: "+char+". ":"")+"Scene: "+scene.text.slice(0,1200)+". No speech bubbles, no captions, no watermark, detailed environment, expressive faces, coherent lighting."}
function save(name,data,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function App(){
const[text,setText]=useState(""),[fileName,setFileName]=useState(""),[style,setStyle]=useState("storybook"),[ratio,setRatio]=useState("portrait"),[character,setCharacter]=useState(""),[scenes,setScenes]=useState([]),[selected,setSelected]=useState(1),[busy,setBusy]=useState(false),[error,setError]=useState(""),[imageMode,setImageMode]=useState("prompts");
const selectedStyle=STYLES.find(x=>x[0]===style)?.[1]||"Hand-drawn Storybook";
const prompts=useMemo(()=>scenes.map(s=>({...s,prompt:promptFor(s,selectedStyle,ratio,character)})),[scenes,selectedStyle,ratio,character]);
const active=scenes.find(s=>s.id===selected)||scenes[0];
async function upload(e){const f=e.target.files?.[0];if(!f)return;setBusy(true);setError("");try{setText(await readFile(f));setFileName(f.name)}catch(x){setError(x.message||"Could not read file.")}finally{setBusy(false)}}
function generate(){if(!text.trim()){setError("Upload a document or paste a story first.");return}setError("");const s=splitScenes(text);setScenes(s);setSelected(1)}
function imageUrl(p){const w=ratio==="landscape"?1280:ratio==="square"?1024:768,h=ratio==="portrait"?1024:ratio==="square"?1024:768;return "https://image.pollinations.ai/prompt/"+encodeURIComponent(p.prompt)+"?width="+w+"&height="+h+"&nologo=true"}
function exportJson(){save("storybook-forge-project.json",JSON.stringify({title:fileName||"Untitled Story",style:selectedStyle,ratio,character,scenes:prompts,createdAt:new Date().toISOString()},null,2),"application/json")}
function exportHtml(){let body="";prompts.forEach(s=>{body+="<section><h2>"+s.title+"</h2><p>"+s.text.replace(/</g,"&lt;")+"</p>"+(imageMode==="images"?"<img src='"+imageUrl(s)+"' alt='"+s.title+"'/>":"")+"</section>"});const html="<!doctype html><html><head><meta charset='utf-8'><title>Storybook Forge</title><style>body{max-width:900px;margin:auto;font:18px Georgia;background:#111;color:#eee;padding:32px}section{page-break-after:always}img{max-width:100%;display:block;margin:20px auto}</style></head><body><h1>"+(fileName||"Illustrated Storybook")+"</h1>"+body+"</body></html>";save("illustrated-storybook.html",html,"text/html")}
return <div className="app"><header><div><div className="eyebrow">FREE-FIRST CREATIVE TOOL</div><h1>Storybook Forge</h1><p>Turn PDF, DOCX, TXT or Markdown into an illustrated-novel blueprint.</p></div><div className="badge">LOCAL • NO ACCOUNT</div></header><main>
<section className="panel input"><div className="drop"><input id="file" type="file" accept=".pdf,.docx,.txt,.md" onChange={upload}/><label htmlFor="file">📚 Choose a story file</label><span>{fileName||"or paste text below"}</span></div><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste your manuscript, chapter, script, or notes here..."/><div className="grid">
<label>Art style<select value={style} onChange={e=>setStyle(e.target.value)}>{STYLES.map(x=><option value={x[0]} key={x[0]}>{x[1]}</option>)}</select></label>
<label>Page shape<select value={ratio} onChange={e=>setRatio(e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option><option value="square">Square</option></select></label>
<label>Character continuity<input value={character} onChange={e=>setCharacter(e.target.value)} placeholder="e.g. white hair, blue eyes..."/></label>
<label>Generation mode<select value={imageMode} onChange={e=>setImageMode(e.target.value)}><option value="prompts">Free prompt studio</option><option value="images">Image preview</option></select></label></div>
<button className="primary" onClick={generate} disabled={busy}>{busy?"Reading…":"✨ Build illustrated scenes"}</button>{error&&<div className="error">{error}</div>}</section>
{scenes.length>0&&<section className="workspace"><aside className="panel scenes"><div className="sectionTitle"><b>Scenes</b><span>{scenes.length}</span></div>{scenes.map(s=><button className={s.id===selected?"scene active":"scene"} onClick={()=>setSelected(s.id)} key={s.id}><strong>{String(s.id).padStart(2,"0")}</strong><span>{s.text.slice(0,90)}…</span></button>)}</aside>
<article className="panel editor">{active&&<><div className="sectionTitle"><div><div className="eyebrow">ILLUSTRATION PROMPT</div><h2>{active.title}</h2></div><span>{active.text.length} chars</span></div><div className="story">{active.text}</div><div className="prompt"><b>Generation prompt</b><textarea value={prompts.find(x=>x.id===active.id)?.prompt||""} readOnly/></div>{imageMode==="images"&&<img className="preview" src={imageUrl(prompts.find(x=>x.id===active.id)||active)} alt="Generated scene preview"/>}<div className="actions"><button onClick={()=>save("scene-"+active.id+"-prompt.txt",prompts.find(x=>x.id===active.id)?.prompt||"")}>Save prompt</button><button onClick={()=>navigator.clipboard?.writeText(prompts.find(x=>x.id===active.id)?.prompt||"")}>Copy prompt</button></div></>}</article></section>}
{scenes.length>0&&<section className="panel export"><div><b>Export your work</b><p>Core generation runs in your browser. No paid backend is required.</p></div><div className="actions"><button onClick={exportJson}>Export JSON</button><button onClick={exportHtml}>Export illustrated HTML</button></div></section>}</main><footer>Storybook Forge • free-first • manuscript parsing stays in your browser.</footer></div>}
export default App;